TesteSmartHint.Web/Controllers/ConfigController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TesteSmartHint.Domain.Entities;
using TesteSmartHint.Domain.Interfaces;
using TesteSmartHint.Domain.Services;
using TesteSmartHint.Web.ViewModels.Config;

namespace TesteSmartHint.Web.Controllers
{
    public class ConfigController : Controller
    {
        private readonly IConfigService _configService;
        private readonly IMapper _mapper;

        public ConfigController(
            IConfigService configService,
            IMapper mapper
        )
        {
            _configService = configService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var config = _mapper.Map<ConfigViewModel>(_configService.GetByName("StateRegistrationForNaturalPerson"));
            return View(config);
        }

        [HttpPost]
        public IActionResult Save(ConfigViewModel model)
        {
            var entity = _configService.GetById(model.Id);
            entity.Value = model.Value;
            _configService.Update(entity);

            TempData["SuccessMessage"] = $"Configurações salvas!";

            return RedirectToAction("Index", "Customer");
        }
    }
}

TesteSmartHint.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TesteSmartHint</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TesteSmartHint</a>
            </div>
            <a class="btn btn-primary" data-toggle="tooltip" title="Configurações" asp-area="" asp-controller="Config" asp-action="Index">
                <i class="bi bi-gear"></i>
            </a>
        </nav>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2023 - TesteSmartHint
        </div>
    </footer>

    <div class="toast-container position-fixed bottom-0 end-0 p-3">
        <div id="notificationToast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="toast-header">
                <i id="toastIcon"></i>
                <strong id="toastTitle" class="me-auto"></strong>
                <button type="button" class="toast-close" data-bs-dismiss="toast" aria-label="Close">
                    <i class="bi bi-x-lg"></i>
                </button>
            </div>
            <div id="toastMessage" class="toast-body">
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script>
        $(document).ready(function () {
            var errorMessage = "@Html.Raw(TempData["ErrorMessage"])";
            var successMessage = "@Html.Raw(TempData["SuccessMessage"])";

            $("#notificationToast").removeClass();
            $("#toastIcon").removeClass();

            if(errorMessage) {
                $("#toastTitle").text("Erro!");
                $("#toastMessage").text(errorMessage);
                $("#notificationToast").addClass("toast error-toast");
                $("#toastIcon").addClass("bi bi-exclamation-diamond");
            }
            else if(successMessage) {
                $("#toastTitle").text("Sucesso!");
                $("#toastMessage").text(successMessage);
                $("#notificationToast").addClass("toast success-toast");
                $("#toastIcon").addClass("bi bi-check-circle");
            }
            
            $("#notificationToast").toast("show");
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>